// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using users_api.DAL.EF;

#nullable disable

namespace users_api.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20231006095553_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("users_api.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1e5b6ec-c1e7-4ac1-803e-af69ee9eef96"),
                            Age = 20,
                            Email = "vladislav@gmail.com",
                            Name = "Vladislav",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("947916c2-6da3-41d8-9b31-ef67601571c0"),
                            Age = 21,
                            Email = "ivan@gmail.com",
                            Name = "Ivan",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("decd1896-bd1c-4f45-8452-33f51d358c1c"),
                            Age = 22,
                            Email = "aleksandr@gmail.com",
                            Name = "Aleksandr",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("0aafc078-c502-4e7f-99d0-a729be33dbad"),
                            Age = 35,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
